/**
 * PostgreSQL counterpart of the `MIGRATIONS` list in `db.ts`.
 *
 * One entry per SQLite migration, in the same order, finishing on the
 * same `app_meta.schema_version` row — so a database's schema version
 * never depends on which dialect wrote it, and the two can be compared
 * directly (`schema-conformance.test.ts` does exactly that).
 *
 * Porting rules, applied mechanically and then checked by that test:
 *
 * - `TEXT` stays `TEXT`. Every JSON blob, id, hash and encrypted payload
 *   in this schema is TEXT; none of them are bytea candidates, because
 *   the encryption format (`v1:iv:tag:ct`, and `scrypt$…` for passwords)
 *   is ASCII by construction.
 * - Epoch-millisecond columns become `BIGINT`. PostgreSQL `INTEGER` is
 *   32-bit and overflows in January 1970 + 24 days worth of
 *   milliseconds, which is not far enough to store `Date.now()`.
 *   Counters, flags and versions stay `INTEGER` — they are compared with
 *   `=== 1` at about twenty call sites and must keep coming back as
 *   numbers, which they do either way.
 * - `INTEGER PRIMARY KEY AUTOINCREMENT` becomes `GENERATED BY DEFAULT AS
 *   IDENTITY`. `BY DEFAULT` rather than `ALWAYS` because the data
 *   migration copies `execution_events.seq` verbatim from SQLite, and
 *   an explicit value has to be accepted on that column.
 * - `COLLATE NOCASE` becomes `LOWER(...)`. SQLite folds case inside the
 *   index; PostgreSQL indexes the expression instead. The three queries
 *   that read through it are rewritten to match (see `db.ts`).
 * - SQLite's implicit `sqlite_autoindex_*` names do not survive: unique
 *   constraints take PostgreSQL's `<table>_<columns>_key` naming. The
 *   conformance test therefore compares indexes by their column sets,
 *   which is what a missing index actually changes.
 *
 * Statements keep SQLite's `?` placeholders where any appear; the facade
 * translates them to `$n` before they reach the driver. (DDL has none —
 * every migration here is parameter-free, which is what lets a whole
 * migration run as one simple-protocol statement and therefore as one
 * implicit transaction.)
 *
 * The SQLite originals stay where they are: they are the rollback
 * artifact and the source this port was checked against, not dead code.
 */

export interface PostgresMigration {
  version: number;
  sql: string;
}

export const MIGRATIONS_PG: PostgresMigration[] = [
  {
    version: 1,
    sql: `
  CREATE TABLE IF NOT EXISTS app_meta (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS workspaces (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT NOT NULL,
    created_at BIGINT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS workspace_members (
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    PRIMARY KEY (workspace_id, user_id)
  );

  CREATE TABLE IF NOT EXISTS workflows (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    name TEXT NOT NULL,
    status TEXT NOT NULL,
    trigger_type TEXT NOT NULL,
    node_count INTEGER NOT NULL DEFAULT 0,
    latest_version INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS workflow_versions (
    id TEXT PRIMARY KEY,
    workflow_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    version INTEGER NOT NULL,
    hash TEXT NOT NULL,
    definition TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    CONSTRAINT uq_workflow_versions_workflow_version UNIQUE (workflow_id, version)
  );

  CREATE TABLE IF NOT EXISTS executions (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    workflow_name TEXT NOT NULL,
    workflow_version_id TEXT NOT NULL,
    workflow_version INTEGER NOT NULL,
    status TEXT NOT NULL,
    trigger_type TEXT NOT NULL,
    trigger_label TEXT NOT NULL,
    source TEXT NOT NULL DEFAULT 'manual',
    started_at BIGINT NOT NULL,
    completed_at BIGINT,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    input TEXT,
    output TEXT,
    error TEXT,
    note TEXT,
    metadata TEXT,
    step_count INTEGER NOT NULL DEFAULT 0,
    failed_step_count INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL
  );

  CREATE TABLE IF NOT EXISTS execution_steps (
    id TEXT PRIMARY KEY,
    execution_id TEXT NOT NULL,
    seq INTEGER NOT NULL,
    node_id TEXT NOT NULL,
    node_type TEXT NOT NULL,
    node_label TEXT NOT NULL,
    ref TEXT NOT NULL,
    status TEXT NOT NULL,
    attempt INTEGER NOT NULL DEFAULT 1,
    started_at BIGINT,
    completed_at BIGINT,
    duration_ms BIGINT NOT NULL DEFAULT 0,
    input TEXT,
    output TEXT,
    error TEXT,
    branch TEXT,
    metadata TEXT
  );

  CREATE TABLE IF NOT EXISTS execution_events (
    seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id TEXT NOT NULL,
    type TEXT NOT NULL,
    at BIGINT NOT NULL,
    data TEXT NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_executions_ws
    ON executions (workspace_id, started_at DESC);
  CREATE INDEX IF NOT EXISTS idx_executions_workflow
    ON executions (workflow_id, started_at DESC);
  CREATE INDEX IF NOT EXISTS idx_steps_execution
    ON execution_steps (execution_id, seq);
  CREATE INDEX IF NOT EXISTS idx_events_execution
    ON execution_events (execution_id, seq);
  `,
  },
  {
    version: 2,
    sql: `
  ALTER TABLE executions ADD COLUMN cancel_requested INTEGER NOT NULL DEFAULT 0;

  CREATE TABLE IF NOT EXISTS webhooks (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    slug TEXT NOT NULL,
    path TEXT NOT NULL,
    method TEXT NOT NULL DEFAULT 'POST',
    auth TEXT NOT NULL DEFAULT 'none',
    secret_enc TEXT,
    enabled INTEGER NOT NULL DEFAULT 0,
    sample TEXT,
    delivery_count INTEGER NOT NULL DEFAULT 0,
    last_delivery_at BIGINT,
    last_delivery_status TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );

  CREATE UNIQUE INDEX IF NOT EXISTS idx_webhooks_slug ON webhooks (slug);
  CREATE INDEX IF NOT EXISTS idx_webhooks_workflow ON webhooks (workflow_id);

  CREATE TABLE IF NOT EXISTS credentials (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    name TEXT NOT NULL,
    kind TEXT NOT NULL,
    secret_enc TEXT NOT NULL,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_credentials_ws ON credentials (workspace_id, kind);
  `,
  },
  {
    version: 3,
    sql: `
  ALTER TABLE credentials ADD COLUMN status TEXT NOT NULL DEFAULT 'connected';
  ALTER TABLE credentials ADD COLUMN account TEXT;
  ALTER TABLE credentials ADD COLUMN scopes TEXT;
  ALTER TABLE credentials ADD COLUMN expires_at BIGINT;
  ALTER TABLE credentials ADD COLUMN last_error TEXT;

  CREATE TABLE IF NOT EXISTS oauth_states (
    state TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    code_verifier TEXT,
    redirect_path TEXT,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    used INTEGER NOT NULL DEFAULT 0
  );

  CREATE INDEX IF NOT EXISTS idx_oauth_states_expiry ON oauth_states (expires_at);

  CREATE TABLE IF NOT EXISTS provider_webhooks (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    workflow_version_id TEXT,
    credential_id TEXT,
    target TEXT NOT NULL,
    events TEXT NOT NULL,
    url_key TEXT NOT NULL,
    secret_enc TEXT NOT NULL,
    mode TEXT NOT NULL DEFAULT 'managed',
    status TEXT NOT NULL DEFAULT 'pending',
    remote_hook_id TEXT,
    last_error TEXT,
    delivery_count INTEGER NOT NULL DEFAULT 0,
    last_delivery_at BIGINT,
    last_delivery_status TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );

  CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_webhooks_key
    ON provider_webhooks (url_key);
  CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_webhooks_workflow
    ON provider_webhooks (provider, workflow_id);

  CREATE TABLE IF NOT EXISTS provider_deliveries (
    provider TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    delivery_id TEXT NOT NULL,
    execution_id TEXT,
    received_at BIGINT NOT NULL,
    PRIMARY KEY (provider, workflow_id, delivery_id)
  );

  CREATE TABLE IF NOT EXISTS provider_watches (
    id TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    credential_id TEXT NOT NULL,
    topic TEXT,
    history_id TEXT,
    cursor TEXT,
    status TEXT NOT NULL DEFAULT 'idle',
    last_error TEXT,
    expires_at BIGINT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );

  CREATE UNIQUE INDEX IF NOT EXISTS idx_provider_watches_credential
    ON provider_watches (provider, credential_id);
  `,
  },
  {
    version: 4,
    sql: `
  CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    password_hash TEXT,
    system INTEGER NOT NULL DEFAULT 0,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );

  CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email ON users (LOWER(email));

  CREATE TABLE IF NOT EXISTS sessions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    token_hash TEXT NOT NULL,
    active_workspace_id TEXT,
    created_at BIGINT NOT NULL,
    expires_at BIGINT NOT NULL,
    last_seen_at BIGINT NOT NULL,
    ip TEXT,
    user_agent TEXT
  );

  CREATE UNIQUE INDEX IF NOT EXISTS idx_sessions_token ON sessions (token_hash);
  CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions (user_id);
  CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON sessions (expires_at);

  CREATE TABLE IF NOT EXISTS audit_events (
    id TEXT PRIMARY KEY,
    workspace_id TEXT,
    actor_id TEXT,
    action TEXT NOT NULL,
    resource_type TEXT,
    resource_id TEXT,
    metadata TEXT,
    ip TEXT,
    user_agent TEXT,
    created_at BIGINT NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_audit_workspace
    ON audit_events (workspace_id, created_at DESC);
  CREATE INDEX IF NOT EXISTS idx_audit_actor
    ON audit_events (actor_id, created_at DESC);

  CREATE UNIQUE INDEX IF NOT EXISTS idx_workspaces_slug ON workspaces (slug);
  CREATE INDEX IF NOT EXISTS idx_members_user ON workspace_members (user_id);
  CREATE INDEX IF NOT EXISTS idx_workflows_workspace
    ON workflows (workspace_id, updated_at DESC);
  CREATE INDEX IF NOT EXISTS idx_workflow_versions_workspace
    ON workflow_versions (workspace_id);
  CREATE INDEX IF NOT EXISTS idx_webhooks_workspace ON webhooks (workspace_id);
  CREATE INDEX IF NOT EXISTS idx_provider_webhooks_workspace
    ON provider_webhooks (workspace_id);
  `,
  },
  {
    version: 5,
    sql: `
  ALTER TABLE workflows ADD COLUMN description TEXT NOT NULL DEFAULT '';
  ALTER TABLE workflows ADD COLUMN draft TEXT NOT NULL DEFAULT '{}';
  ALTER TABLE workflows ADD COLUMN draft_revision INTEGER NOT NULL DEFAULT 0;
  ALTER TABLE workflows ADD COLUMN published_version_id TEXT;
  ALTER TABLE workflows ADD COLUMN published_version INTEGER NOT NULL DEFAULT 0;
  ALTER TABLE workflows ADD COLUMN created_by TEXT;
  ALTER TABLE workflows ADD COLUMN updated_by TEXT;
  ALTER TABLE workflows ADD COLUMN archived_at BIGINT;

  ALTER TABLE workflow_versions ADD COLUMN created_by TEXT;

  CREATE INDEX IF NOT EXISTS idx_workflows_active
    ON workflows (workspace_id, archived_at, updated_at DESC);

  /* Backfill: whatever a workflow was running becomes the published
     version, and its definition becomes the editable draft. */
  UPDATE workflows
     SET published_version = latest_version
   WHERE latest_version > 0 AND published_version = 0;

  UPDATE workflows
     SET published_version_id = (
           SELECT v.id FROM workflow_versions v
            WHERE v.workflow_id = workflows.id
              AND v.version = workflows.published_version
            LIMIT 1
         )
   WHERE published_version_id IS NULL AND published_version > 0;

  UPDATE workflows
     SET draft = (
           SELECT v.definition FROM workflow_versions v
            WHERE v.workflow_id = workflows.id
              AND v.version = workflows.published_version
            LIMIT 1
         )
   WHERE draft = '{}' AND published_version > 0;
  `,
  },
  {
    version: 6,
    sql: `
  CREATE TABLE IF NOT EXISTS workflow_triggers (
    id TEXT PRIMARY KEY,
    workflow_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    type TEXT NOT NULL,
    enabled INTEGER NOT NULL DEFAULT 1,
    config TEXT NOT NULL DEFAULT '{}',
    schedule_cron TEXT,
    schedule_timezone TEXT,
    next_run_at BIGINT,
    last_fire_at BIGINT,
    last_execution_id TEXT,
    last_status TEXT,
    last_error TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );

  CREATE UNIQUE INDEX IF NOT EXISTS idx_workflow_triggers_workflow
    ON workflow_triggers (workflow_id);
  CREATE INDEX IF NOT EXISTS idx_workflow_triggers_due
    ON workflow_triggers (type, enabled, next_run_at);

  CREATE TABLE IF NOT EXISTS trigger_fires (
    trigger_id TEXT NOT NULL,
    workspace_id TEXT NOT NULL,
    workflow_id TEXT NOT NULL,
    occurrence_key TEXT NOT NULL,
    fired_at BIGINT NOT NULL,
    status TEXT NOT NULL DEFAULT 'claimed',
    execution_id TEXT,
    error TEXT,
    PRIMARY KEY (trigger_id, occurrence_key)
  );

  CREATE INDEX IF NOT EXISTS idx_trigger_fires_workflow
    ON trigger_fires (workflow_id, fired_at DESC);
  CREATE INDEX IF NOT EXISTS idx_trigger_fires_execution
    ON trigger_fires (execution_id);
  `,
  },
  {
    version: 7,
    sql: `
  CREATE TABLE IF NOT EXISTS templates (
    id TEXT PRIMARY KEY,
    workspace_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    category TEXT NOT NULL DEFAULT 'general',
    icon TEXT NOT NULL DEFAULT 'workflow',
    definition TEXT NOT NULL,
    node_count INTEGER NOT NULL DEFAULT 0,
    trigger_type TEXT NOT NULL DEFAULT '',
    integrations TEXT NOT NULL DEFAULT '[]',
    required_credentials TEXT NOT NULL DEFAULT '[]',
    system INTEGER NOT NULL DEFAULT 0,
    created_by TEXT,
    created_at BIGINT NOT NULL,
    updated_at BIGINT NOT NULL
  );

  CREATE INDEX IF NOT EXISTS idx_templates_workspace
    ON templates (workspace_id, updated_at DESC);
  CREATE INDEX IF NOT EXISTS idx_templates_category
    ON templates (workspace_id, category);
  `,
  },
];
