import { CONDITION_OPERATORS } from "@/lib/engine/conditions";
import type { NodeDefinition } from "@/lib/workflow/types";
import { AGGREGATE_FNS, OPERATIONS } from "./operations";

const OPERATOR_OPTIONS: { value: string; label: string }[] = [
  { value: "eq", label: "equals" },
  { value: "neq", label: "does not equal" },
  { value: "contains", label: "contains" },
  { value: "notContains", label: "does not contain" },
  { value: "startsWith", label: "starts with" },
  { value: "endsWith", label: "ends with" },
  { value: "gt", label: "is greater than" },
  { value: "gte", label: "is greater than or equal" },
  { value: "lt", label: "is less than" },
  { value: "lte", label: "is less than or equal" },
  { value: "exists", label: "exists" },
  { value: "notExists", label: "does not exist" },
  { value: "matches", label: "matches regex" },
].filter((option) => (CONDITION_OPERATORS as readonly string[]).includes(option.value));

/** JSON-ish mapping — the original Transform node. */
export const transformDefinition: NodeDefinition = {
  type: "logic.transform",
  category: "logic",
  title: "Transform",
  description: "Reshapes data before it reaches the next step.",
  icon: "braces",
  summary: "Reshapes data",
  cost: 6,
  fields: [
    {
      key: "mapping",
      label: "Mapping",
      kind: "code",
      required: true,
      rows: 8,
      mono: true,
      bindable: true,
      placeholder: '{\n  "email": {{github.issue.author}},\n  "title": {{github.issue.title}}\n}',
      help: "JSON with {{references}} for values. The result is available as an object to later steps.",
    },
  ],
  outputs: [{ key: "value", label: "Value", type: "object" }],
};

/** List/value operations — filter, map, sort, aggregate, JSON. */
export const operationsDefinition: NodeDefinition = {
  type: "logic.operations",
  category: "data",
  title: "Data transform",
  description: "Filters, reshapes and aggregates lists with real operations.",
  icon: "list",
  summary: "Reshapes a list",
  cost: 8,
  fields: [
    {
      key: "input",
      label: "Input",
      kind: "expression",
      required: true,
      bindable: true,
      placeholder: "{{http.body.items}}",
      help: "The list (or value) the operation works on.",
    },
    {
      key: "operation",
      label: "Operation",
      kind: "select",
      required: true,
      options: OPERATIONS.map((operation) => ({
        value: operation.id,
        label: operation.label,
      })),
      help: "Pick one — the fields below change to match.",
    },
    {
      key: "left",
      label: "Field",
      kind: "expression",
      required: true,
      bindable: true,
      showWhen: { key: "operation", equals: "filter" },
      placeholder: "status",
      help: "A path inside each item (status, profile.email) or an expression ({{item.email}}). Paths fall back to the run scope.",
    },
    {
      key: "operator",
      label: "Operator",
      kind: "select",
      required: true,
      showWhen: { key: "operation", equals: "filter" },
      options: OPERATOR_OPTIONS,
    },
    {
      key: "value",
      label: "Value",
      kind: "expression",
      bindable: true,
      showWhen: { key: "operation", equals: "filter" },
      help: "Compared against the field. Expressions resolve per item.",
    },
    {
      key: "fields",
      label: "Output fields",
      kind: "keyvalue",
      required: true,
      bindable: true,
      showWhen: { key: "operation", equals: "map" },
      help: "Name → expression, e.g. email → {{item.contact.email}}.",
    },
    {
      key: "keys",
      label: "Fields to keep",
      kind: "text",
      mono: true,
      required: true,
      showWhen: { key: "operation", equals: "pick" },
      placeholder: "id, email, profile.name",
    },
    {
      key: "mappings",
      label: "Renames",
      kind: "keyvalue",
      required: true,
      showWhen: { key: "operation", equals: "rename" },
      help: "New name → current name. Unlisted fields are kept as they are.",
    },
    {
      key: "by",
      label: "By",
      kind: "text",
      mono: true,
      required: true,
      showWhen: { key: "operation", equals: ["sort", "dedupe"] },
      placeholder: "created_at",
      help: "Field path. Leave blank only for de-duplicating whole items.",
    },
    {
      key: "direction",
      label: "Direction",
      kind: "select",
      showWhen: { key: "operation", equals: "sort" },
      options: [
        { value: "asc", label: "Ascending" },
        { value: "desc", label: "Descending" },
      ],
    },
    {
      key: "depth",
      label: "Depth",
      kind: "number",
      showWhen: { key: "operation", equals: "flatten" },
      placeholder: "1",
    },
    {
      key: "offset",
      label: "Offset",
      kind: "number",
      showWhen: { key: "operation", equals: "slice" },
      placeholder: "0",
    },
    {
      key: "limit",
      label: "Limit",
      kind: "number",
      showWhen: { key: "operation", equals: "slice" },
      placeholder: "50",
    },
    {
      key: "fn",
      label: "Function",
      kind: "select",
      required: true,
      showWhen: { key: "operation", equals: "aggregate" },
      options: AGGREGATE_FNS.map((fn) => ({ value: fn, label: fn })),
    },
    {
      key: "path",
      label: "Field path",
      kind: "text",
      mono: true,
      showWhen: { key: "operation", equals: ["aggregate", "get"] },
      placeholder: "amount",
      help: "Required for sum/avg/min/max and Get. Blank counts every item.",
    },
  ],
  outputs: [
    { key: "value", label: "Value", type: "object" },
    { key: "count", label: "Count", type: "number" },
  ],
};
