import type { NodeDefinition } from "@/lib/workflow/types";

const OPERATION_OPTIONS = [
  { value: "query", label: "Raw SQL" },
  { value: "select", label: "Select rows" },
  { value: "insert", label: "Insert rows" },
  { value: "update", label: "Update rows" },
];

/** Run a parameterised statement (SQL or generated from the builder). */
export const postgresActionDefinition: NodeDefinition = {
  type: "action.postgres",
  category: "action",
  title: "PostgreSQL",
  description: "Runs a parameterised query against a connected database.",
  icon: "database",
  summary: "Runs a query",
  cost: 88,
  credentials: ["postgres"],
  fields: [
    {
      key: "credential",
      label: "Credential",
      kind: "credential",
      required: true,
      help: "Connection details are stored encrypted and never leave the worker.",
    },
    {
      key: "operation",
      label: "Operation",
      kind: "select",
      required: true,
      options: OPERATION_OPTIONS,
      help: "Raw SQL lets you write the statement; the others build safe parameterised SQL from the fields below.",
    },
    {
      key: "query",
      label: "Query",
      kind: "code",
      rows: 7,
      mono: true,
      showWhen: { key: "operation", equals: "query" },
      placeholder: "insert into leads (email, source)\nvalues ($1, $2)\nreturning id",
      help: "Single statement only; use $1, $2 … for values.",
    },
    {
      key: "params",
      label: "Parameters",
      kind: "keyvalue",
      bindable: true,
      showWhen: { key: "operation", equals: "query" },
    },
    {
      key: "readMode",
      label: "Return",
      kind: "select",
      showWhen: { key: "operation", equals: "query" },
      options: [
        { value: "rows", label: "Rows" },
        { value: "count", label: "Row count" },
        { value: "none", label: "Nothing" },
      ],
    },
    {
      key: "table",
      label: "Table",
      kind: "text",
      mono: true,
      required: true,
      showWhen: { key: "operation", equals: ["select", "insert", "update"] },
      placeholder: "public.leads",
      help: "Schema-qualified names are allowed (schema.table); identifiers are validated.",
    },
    {
      key: "columns",
      label: "Columns",
      kind: "text",
      mono: true,
      showWhen: { key: "operation", equals: "select" },
      placeholder: "id, email, created_at  (blank = all)",
    },
    {
      key: "where",
      label: "Where",
      kind: "keyvalue",
      bindable: true,
      showWhen: { key: "operation", equals: ["select", "update"] },
      help: "Each row becomes `column = $n` — values are bound, never interpolated.",
    },
    {
      key: "orderBy",
      label: "Order by",
      kind: "text",
      mono: true,
      showWhen: { key: "operation", equals: "select" },
      placeholder: "created_at desc",
    },
    {
      key: "limit",
      label: "Row limit",
      kind: "number",
      showWhen: { key: "operation", equals: "select" },
      placeholder: "100",
    },
    {
      key: "values",
      label: "Values",
      kind: "keyvalue",
      bindable: true,
      required: true,
      showWhen: { key: "operation", equals: "insert" },
      help: "Column → value. Values become $1, $2 …",
    },
    {
      key: "returning",
      label: "Returning",
      kind: "text",
      mono: true,
      showWhen: { key: "operation", equals: "insert" },
      placeholder: "id, created_at",
    },
    {
      key: "set",
      label: "Set",
      kind: "keyvalue",
      bindable: true,
      required: true,
      showWhen: { key: "operation", equals: "update" },
      help: "Column → new value. A WHERE clause is required.",
    },
  ],
  outputs: [
    { key: "rows", label: "Rows", type: "array" },
    { key: "rowCount", label: "Row count", type: "number" },
  ],
};

/** Read rows so later steps can reference them. */
export const postgresReadDefinition: NodeDefinition = {
  type: "data.postgres",
  category: "data",
  title: "PostgreSQL read",
  description: "Reads rows so later steps can use them.",
  icon: "database",
  summary: "Reads rows",
  cost: 74,
  credentials: ["postgres"],
  fields: [
    {
      key: "credential",
      label: "Credential",
      kind: "credential",
      required: true,
    },
    {
      key: "query",
      label: "Query",
      kind: "code",
      required: true,
      rows: 6,
      mono: true,
      bindable: true,
      placeholder: "select * from accounts where id = $1",
      help: "Single SELECT (or WITH) statement; use $1, $2 … for values.",
    },
    { key: "params", label: "Parameters", kind: "keyvalue", bindable: true },
    {
      key: "limit",
      label: "Row limit",
      kind: "number",
      placeholder: "100",
      help: "Applied in the database (the query is wrapped), so large tables are not pulled into memory.",
    },
  ],
  outputs: [
    { key: "rows", label: "Rows", type: "array" },
    { key: "rowCount", label: "Row count", type: "number" },
  ],
};
