import { Pool, type PoolConfig, type QueryResult } from "pg";
import { decryptCredentialFields } from "@/lib/server/credentials";
import { redactMessage } from "@/lib/server/redact";
import type { NodeHandler, NodeRunContext } from "@/lib/engine/types";
import { POSTGRES_ERRORS, REMEDIATION, integrationError } from "../errors";
import {
  applyRowLimit,
  assertSafeQuery,
  buildInsert,
  buildSelect,
  buildUpdate,
  type RawQuery,
} from "./sql";

/**
 * PostgreSQL handler.
 *
 * One handler serves both node types. Statements are either validated
 * raw SQL or generated by the builder — always executed through the
 * driver's parameter binding. Each node run opens a short-lived pool and
 * closes it in `finally`, so a crashed run can never leak connections.
 */

const CONNECTION_ERRNOS = new Set([
  "ECONNREFUSED",
  "ENOTFOUND",
  "EHOSTUNREACH",
  "ENETUNREACH",
  "ECONNRESET",
  "ETIMEDOUT",
  "EPIPE",
  "ENOTDIR",
  "EAI_AGAIN",
]);

const CONNECTION_TIMEOUT_MS = 5_000;
const QUERY_TIMEOUT_MS = 12_000;

export const postgresHandler: NodeHandler = async (context: NodeRunContext) => {
  const startedAt = Date.now();
  const { config, workspaceId } = context;

  const credentialId = typeof config.credential === "string" ? config.credential.trim() : "";
  if (!credentialId) {
    throw integrationError(
      POSTGRES_ERRORS.credentialInvalid,
      "This PostgreSQL step has no credential selected.",
      { hint: "Pick a stored PostgreSQL credential for the node." },
    );
  }

  const fields = decrypt(workspaceId, credentialId);
  const poolConfig = connectionConfig(fields);
  const query = buildStatement(config, context.rawConfig ?? config);

  const pool = new Pool({ ...poolConfig, max: 1 });
  try {
    const result = await runQuery(pool, query);
    const rows = result.rows ?? [];
    const limited =
      rows.length > 10_000 ? rows.slice(0, 10_000) : rows;
    const readMode = String(config.readMode ?? "rows");
    const wantsRows = readMode !== "count" && readMode !== "none";

    return {
      output: {
        rows: wantsRows ? limited : [],
        rowCount: result.rowCount ?? rows.length,
        durationMs: Date.now() - startedAt,
      },
    };
  } finally {
    await pool.end().catch(() => undefined);
  }
};

/* ------------------------------------------------------------------ */
/* Statement construction                                              */
/* ------------------------------------------------------------------ */

function buildStatement(
  config: Record<string, unknown>,
  rawConfig: Record<string, unknown>,
): RawQuery {
  const operation = String(config.operation ?? "query").toLowerCase();

  if (operation === "select") {
    return buildSelect({
      table: String(config.table ?? ""),
      columns: typeof config.columns === "string" ? config.columns : undefined,
      where: keyvalue(config.where),
      orderBy: typeof config.orderBy === "string" ? config.orderBy : undefined,
      limit: numberOr(config.limit, 0),
    });
  }
  if (operation === "insert") {
    return buildInsert({
      table: String(config.table ?? ""),
      values: keyvalue(config.values),
      returning: typeof config.returning === "string" ? config.returning : undefined,
    });
  }
  if (operation === "update") {
    return buildUpdate({
      table: String(config.table ?? ""),
      set: keyvalue(config.set),
      where: keyvalue(config.where),
    });
  }

  const authored =
    typeof rawConfig.query === "string" ? rawConfig.query : String(config.query ?? "");
  if (authored.includes("{{")) {
    throw integrationError(
      POSTGRES_ERRORS.invalidQuery,
      "Expressions cannot be written inside the query.",
      {
        detail:
          "The engine would splice run data into the SQL as text, which is how injections happen.",
        hint: "Move values into Parameters ($1, $2 …) — they are bound by the driver, never interpolated.",
        remediation: REMEDIATION.inspect,
      },
    );
  }
  const sql = assertSafeQuery(authored);
  const params = keyvalue(config.params).map((row) => row.value);
  return applyRowLimit({ sql, params }, numberOr(config.limit, 0));
}

interface KeyValueRow {
  key: string;
  value: unknown;
}

function keyvalue(value: unknown): KeyValueRow[] {
  if (!Array.isArray(value)) return [];
  return value
    .filter((item): item is Record<string, unknown> => !!item && typeof item === "object")
    .map((item) => ({ key: String(item.key ?? ""), value: item.value }))
    .filter((row) => row.key.trim() !== "");
}

function numberOr(value: unknown, fallback: number): number {
  const parsed = typeof value === "number" ? value : Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

/* ------------------------------------------------------------------ */
/* Connection                                                          */
/* ------------------------------------------------------------------ */

function decrypt(workspaceId: string, credentialId: string): Record<string, string> {
  try {
    return decryptCredentialFields(workspaceId, credentialId);
  } catch (error) {
    throw integrationError(
      POSTGRES_ERRORS.credentialInvalid,
      error instanceof Error ? error.message : "The credential could not be read.",
      { remediation: REMEDIATION.reconnect },
    );
  }
}

export function connectionConfig(fields: Record<string, string>): PoolConfig {
  const connectionString = fields.connectionString?.trim();
  const base: PoolConfig = {
    connectionTimeoutMillis: CONNECTION_TIMEOUT_MS,
    query_timeout: QUERY_TIMEOUT_MS,
    max: 1,
    ...(connectionString ? { connectionString } : {
      host: fields.host,
      port: numberOr(fields.port, 5432),
      database: fields.database,
      user: fields.user,
      ...(fields.password ? { password: fields.password } : {}),
    }),
    ...(isTruthy(fields.ssl) ? { ssl: { rejectUnauthorized: false } } : {}),
  };
  if (!connectionString && (!fields.host || !fields.database || !fields.user)) {
    throw integrationError(
      POSTGRES_ERRORS.credentialInvalid,
      "That credential is missing host, database or user.",
      { remediation: REMEDIATION.reconnect },
    );
  }
  return base;
}

function isTruthy(value: string | undefined): boolean {
  const normalised = (value ?? "").trim().toLowerCase();
  return normalised === "1" || normalised === "true" || normalised === "yes" || normalised === "require";
}

async function runQuery(pool: Pool, query: RawQuery): Promise<QueryResult> {
  try {
    return await pool.query(query.sql, query.params);
  } catch (error) {
    throw mapPostgresError(error);
  }
}

export function mapPostgresError(error: unknown): ReturnType<typeof integrationError> {
  if (error instanceof Error && error.name === "EngineError") {
    return error as ReturnType<typeof integrationError>;
  }
  const message = error instanceof Error ? error.message : "Unknown database error";
  const driverCode = typeof error === "object" && error && "code" in error
    ? String((error as { code?: unknown }).code)
    : "";
  const errno = typeof error === "object" && error && "errno" in error
    ? Number((error as { errno?: unknown }).errno)
    : undefined;
  const detail = redactMessage(message);

  if (CONNECTION_ERRNOS.has(driverCode) || (errno !== undefined && CONNECTION_ERRNOS.has(String(errno)))) {
    return integrationError(
      POSTGRES_ERRORS.connectionFailed,
      "Could not reach the database.",
      {
        detail,
        hint: "Check the host/port, that PostgreSQL is running, and that the worker can reach it.",
        remediation: REMEDIATION.retry,
        retryable: true,
      },
    );
  }
  if (/timeout|timed out|canceling statement/i.test(message)) {
    return integrationError(
      POSTGRES_ERRORS.timeout,
      "The query exceeded its time limit.",
      { detail, hint: "Narrow the query (fewer rows, a tighter WHERE clause).", retryable: true },
    );
  }
  const syntaxClass = driverCode.startsWith("42") || driverCode === "22P02";
  return integrationError(
    POSTGRES_ERRORS.queryFailed,
    "The database rejected the statement.",
    {
      detail,
      hint: syntaxClass
        ? "PostgreSQL could not parse the statement or a column/table is missing — check names and placeholders."
        : "Check the data being written (types, constraints) and the parameter values.",
      remediation: REMEDIATION.inspect,
    },
  );
}
